trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10' 
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    displayName: 'Install Dependencies, no cache pour reinstaller'

  
  - script: |
      pip install ruff
      ruff format src/
    displayName: 'Lint code'

  - script: |
      set -x
      echo "Starting deployment..."
      pwd
      ls -la
      python -m pip install --no-cache-dir -r requirements.txt
      echo "Dependencies installed"
      cd src
      echo "Changed directory"
      ls -la
    displayName: 'Run Backend'


  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'fitness-tracker-connection'
      appName: 'fitness-api-backed-001-ahmed2'
      package: '$(System.DefaultWorkingDirectory)'
      appSettings: |
        APP_INSIGHTS_KEY=$(APP_INSIGHTS_KEY)
        AZURE_ML_ENDPOINT=$(AZURE_ML_ENDPOINT)
        AZURE_ML_KEY=$(AZURE_ML_KEY)
        CONNECTION_STRING=$(CONNECTION_STRING)
        DB_PATH=$(DB_PATH)
        PYTHON_PATH=$(PYTHON_PATH)
        SCM_DO_BUILD_DURING_DEPLOYMENT=$(SCM_DO_BUILD_DURING_DEPLOYMENT)
        WEBSITE_RUN_FROM_PACKAGE=$(WEBSITE_RUN_FROM_PACKAGE)
        WEBSITES_PORT=$(WEBSITES_PORT)
