trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'fitness-tracker-connection'
    appName: 'fitness-api-backed-001-ahmed2'
    package: '$(System.DefaultWorkingDirectory)'